server:
  port: 8081
spring:
  application:
    name: client
eureka:
  client:
    service-url:
      defaultZone: http://192.168.163.128:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  sentinel:
    enabled: true
